### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [nvamsikrishna05/prj-rev-bwfs-dasmoto#5]
**GRADE**: Exceeds Expectations

**SUMMARY**: Great work on this project! The site itself looks great and you did an excellent job keeping both the project folder and the code neat, organized, and readable. Excellent work keeping the styling clean and concise as well. 

The only small area for improvement would be the class / id naming structure you've chosen. Use ids to target unique, specific elements. In this project, the unique elements are the h2 items that each get a different background color. Your code works fine here, but using the ids right on the h2 elements would be a bit more straight forward.

Consider organizing the html and css further by making use of some comments throughout. More info about html styling in general can be found here - https://www.w3schools.com/html/html5_syntax.asp

**Comment by nvamsikrishna05** [comment]
Thanks for the feedback. Will keep the things in mind next time.
